#!/usr/bin/env python3
"""Speed reclassification decisions for chunk D (112 routes).
Each entry: (new_speed, when_cash_arrives, maximize, rationale)"""
DECISIONS = {
# ---------------- TODAY ----------------
"R0118": ("today",
 "PayPal usually within ~2 hours (up to 1-3 business days at peak); gift cards within the hour by email. Redeem on demand once balance hits $20 and one qualifying offer is redeemed.",
 "Reach the $20 withdrawal threshold with at least one redeemed offer, then cash out to PayPal or a gift card for same-day money; gift cards are fastest (within the hour).",
 "Official Ibotta help center states PayPal payouts usually land within ~2 hours and gift cards within the hour — redemption itself is on demand, so money arrives same day."),
"R0120": ("today",
 "Pay with Upside cashback credits within minutes of the qualifying purchase; cash out any time with no minimum to a bank account or gift cards.",
 "Use 'Pay with Upside' (pay inside the app) so cashback credits within minutes, then cash out immediately — gift cards are the same-day path, bank transfers add standard processing.",
 "Official Upside pages: 'Pay with Upside' credits cashback within minutes and there is no minimum to cash out, so the balance is withdrawable same day."),
"R0446": ("today",
 "Credit is added on survey completion; there is no separate payout schedule. (Android: Google Play credit; iOS: PayPal.)",
 "Answer surveys as they appear — each completed survey credits the same day. No cashout step to wait on.",
 "Official Google Play listing: 'up to $1.00 in Play credit for completing it' with credit added on survey completion and no payout schedule — same-day credit."),
"R3561": ("today",
 "20% off (up to $100) applied at the time of your first qualifying purchase on the newly opened MyLowe's Rewards Credit Card.",
 "Plan a ~$500 already-planned purchase and use the new card at checkout the day you open it for the full $100 value.",
 "Official Lowe's credit terms: the discount applies at the time of the first qualifying purchase on the new account — value realized same day at checkout."),
"R3562": ("today",
 "Up to $100 off applied to a qualifying purchase when you open and use the new Home Depot Consumer Credit Card.",
 "Open the card and make the qualifying purchase the same day; the discount lands at checkout.",
 "Official Home Depot credit-center page: 'Save up to $100 today on a qualifying purchase when you open a new card' — value realized same day."),
"R3563": ("today",
 "20% off qualifying purchases (up to $100 total savings), valid only on the day of approval.",
 "Get instant approval, then buy up to $500 of already-planned merchandise the same day for the full $100.",
 "Official Macy's terms: the discount is valid only on the day of approval — the value must be captured same day."),
"R6401": ("today",
 "$80 Amazon Gift Card issued upon approval of the Amazon Store Card.",
 "Apply online and get approved — the $80 gift card is issued at approval, no purchase required.",
 "Official amazon.com Store Card page: 'Get an $80 Amazon Gift Card upon approval' — payout is immediate at approval."),
"R6403": ("today",
 "1,000 Bonus Belk Reward Points ($10) applied when a purchase is made the day the account is opened; the 20% first-day coupon is also usable same day.",
 "Open the card and make a Belk purchase the same day it is opened to trigger the $10 bonus points.",
 "Official belk.com terms: bonus points apply when a purchase is made the day the account is opened — same-day value."),
"R6407": ("today",
 "$10 off your first order of $75 or more — free Journeys All Access loyalty signup, no credit card; coupon usable immediately.",
 "Sign up free and place the planned $75+ footwear order the same day.",
 "Official journeys.com page: the $10-off welcome perk is a free loyalty signup, usable on the first order immediately."),
"R6411": ("today",
 "$50 off any online order of $300 or more at email signup — no credit card, no hard inquiry; usable same day.",
 "Sign up with your email and place the planned $300+ Zales order the same day.",
 "Official Zales signup page: $50-off first-order bonus on email signup alone — same-day value."),
"R6430": ("today",
 "$15 off $50 or more new-homeowner coupon — valid online and in store; usable same day.",
 "Use the coupon on planned lighting/decor spending the same day you enroll.",
 "Official lampsplus.com New Homeowner page: fixed-dollar signup coupon, redeemable same day."),
"R6433": ("today",
 "$10 off a $50+ order at Mobile Alerts (SMS) signup — usable same day.",
 "Subscribe to Mobile Alerts and place the planned $50+ Hibbett order the same day.",
 "Official hibbett.com coupon page: $10-off signup coupon for Mobile Alerts subscribers — same-day value."),
# ---------------- DAYS ----------------
"R0438": ("days",
 "PayPal payout in less than 2 days per the developer; redeem on demand.",
 "Build to the cashout level, then redeem on demand via PayPal — lands in under 2 days.",
 "Official Google Play listing (CoinPop): 'You can also cash out on your Paypal account and get your money in less than 2 days.'"),
"R0454": ("days",
 "Bank transfer: up to five business days (other withdrawal methods vary); minimum $20 in current earnings with at least one name-brand offer.",
 "Withdraw to your bank as soon as you hit $20 with a name-brand offer; it lands within ~5 business days.",
 "Official Ibotta help center: bank transfers can take up to five business days."),
"R0457": ("days",
 "Order-confirmation email within 24-72 business hours; gift-card issuance can take up to three business days after that.",
 "Redeem Shopping Rewards and allow up to ~6 business days for the digital gift card to be issued.",
 "Official capitaloneshopping.com help center: 24-72 business-hour confirmation plus up to 3 business days for issuance — fits inside a week."),
"R0119": ("days",
 "Digital gift cards typically delivered within 72 hours of redemption (per official Fetch FAQ).",
 "Redeem points for a digital gift card — it usually arrives within ~3 days of redemption.",
 "Official Fetch FAQ: digital gift cards typically delivered within 72 hours of redemption."),
"R0498": ("days",
 "Rewards paid within ~3-7 business days of redemption (10,000 points = $10).",
 "Redeem once you hit 10,000 points; PayPal/direct deposit lands within ~a week.",
 "Official Evidation FAQ/blog: 10,000 points = $10, paid within ~3-7 business days of redemption."),
"R0515": ("days",
 "Gift code emailed within up to 48 hours of redemption.",
 "Redeem as soon as you have enough Nanas; the gift code lands within ~2 days.",
 "Official Play listing copy: gift code emailed within up to 48 hours of redemption."),
"R0517": ("days",
 "Gift card and PayPal redemptions paid within 2 business days; minimum redemption as low as $1.",
 "Cash out at the $1 minimum via PayPal or gift card — paid within 2 business days.",
 "Official Lootup FAQ: redemption minimum $1.00 and gift card/PayPal redemptions paid within 2 business days."),
"R0838": ("days",
 "Both sides receive $30 in the US Mobile Rewards Center after the friend's activation — advertised as fast payout.",
 "Activate via eSIM (minutes) through a referral link; the $30 credit lands in the Rewards Center fast after activation.",
 "Official usmobile.com referrer page advertises 'fast payout' credited to the Rewards Center after activation."),
"R3569": ("days",
 "$100 Initial Matching Grant awarded automatically after the qualifying $25 contribution; FAME sends a letter or email confirmation.",
 "Open the NextGen 529 account and contribute $25 — the $100 grant is awarded automatically.",
 "Official nextgenforme.com grants page: the $100 Initial Matching Grant is awarded automatically after the qualifying contribution."),
"R6402": ("days",
 "$10 CashPass Reward Certificate deposited into your JCPenney Rewards account within 48 hours of opening the card (no purchase required).",
 "Just open the card — the $10 certificate lands within 2 days. (The $35/$125 coupon needs a first purchase by 11/30/2026.)",
 "Official jcpcreditcard.com apply page: $10 CashPass certificate deposited within 48 hours of account opening."),
# ---------------- WEEKS (structurally slow) ----------------
"R0430": ("weeks",
 "Cash bonus paid within ~7 business days after completing the direct-deposit requirements (25-day window from first eligible deposit).",
 "Complete the qualifying direct deposits early in the 25-day window; the bonus lands ~1 week after completion.",
 "Completing the direct-deposit requirements takes weeks by definition — no same-day path."),
"R0431": ("weeks",
 "No signup bonus exists — earnings accrue only as variable interest while your own funds sit in the account.",
 "None available for a bonus; this is interest-only.",
 "No bonus mechanism exists; interest accrual is inherently slow."),
"R0433": ("weeks",
 "No signup bonus exists — interest compounds daily and is credited monthly.",
 "None available for a bonus; interest-only.",
 "No bonus mechanism exists."),
"R0434": ("weeks",
 "No signup bonus exists — variable APY effective 9/22/2026, interest accrues daily and compounds monthly.",
 "None available for a bonus; interest-only.",
 "No bonus mechanism exists."),
"R0435": ("weeks",
 "No signup bonus exists — interest compounded daily, credited monthly.",
 "None available for a bonus; interest-only.",
 "No bonus mechanism exists."),
"R0436": ("weeks",
 "Bonus credited after the 90-day balance maintenance period (14-day funding window to reach your tier).",
 "Fund to your tier within the 14-day window and hold; the bonus lands after the 90-day maintenance.",
 "The 90-day continuous-balance hold is the structural blocker."),
"R0437": ("weeks",
 "Bonus credited within 30 days of satisfying all requirements; qualifying deposits must be maintained with partner banks for 90 days.",
 "Make qualifying deposits in September and hold; the bonus credits within 30 days after all requirements are met.",
 "The 90-day deposit maintenance period is the structural blocker."),
"R0439": ("weeks",
 "On-demand redemption, but no published payout processing time; the app has not been meaningfully updated since ~2021.",
 "Redeem on demand via PayPal — but expect delays given the app's staleness.",
 "No official payout timing exists, and the app is effectively unmaintained."),
"R0441": ("weeks",
 "Redeem on demand once you hit the minimum; gift cards/PayPal delivered per app terms (concrete minimums not confirmed in official material).",
 "Grind points via app trials and redeem on demand.",
 "Earning to the redemption minimum takes time and official processing time is unstated."),
"R0447": ("weeks",
 "Redeem on demand from $1; gift cards delivered digitally. Figures are reviewer-reported — the official site failed to load this pass.",
 "Cash out at the $1 minimum for a digital gift card.",
 "Official payout terms could not be re-verified (site down); 'unverified' on timing."),
"R0451": ("weeks",
 "First redemption only after 30 days of active use; PayPal or Amazon gift cards (~$5/month).",
 "Install and stay active 30 days, then redeem.",
 "The 30-day active-use gate is the structural blocker."),
"R0452": ("weeks",
 "Monthly cash rewards paid by paper check (slow — weeks to arrive); minimum $1 to request; $3/device/month.",
 "Install on every device to stack the $3/device monthly rate.",
 "Monthly cadence plus paper-check mailing is the structural blocker."),
"R0481": ("weeks",
 "Payouts per Twitch's payout terms after the payout threshold is reached; earnings are only what your viewers actually spend.",
 "Grow subs/bits; the payout cycle is the floor, not the ceiling.",
 "Earning requires an audience and Twitch's threshold — payout speed is not the bottleneck."),
"R0482": ("weeks",
 "Payouts monthly via Patreon's payout system; earnings accumulate only when patrons pay.",
 "Launch tiers and get patrons paying.",
 "Patron revenue and monthly payouts are the structural blockers."),
"R0483": ("weeks",
 "Payments go directly to your connected PayPal/Stripe as supporters pay — no platform payout cycle.",
 "Link PayPal/Stripe so tips land immediately when supporters pay; the fast path is on the payout rail.",
 "Getting supporters is the blocker — the payout rail itself is instant."),
"R0485": ("weeks",
 "Paid subscriptions pay out via Stripe as revenue comes in (Substack's 10% deducted).",
 "Get paid subscribers.",
 "Subscriber revenue is the blocker."),
"R0486": ("weeks",
 "Weekly payouts after a holding period, subject to a minimum balance.",
 "Sell digital products; payouts go weekly once past the hold.",
 "The holding period and minimum balance are the structural blockers."),
"R0488": ("weeks",
 "Payouts monthly (around the 10th); funds accumulate only when your assets sell.",
 "List in-demand assets.",
 "Asset sales and the monthly payout are the structural blockers."),
"R0490": ("weeks",
 "Earnings available for withdrawal 14 days after an order is marked complete (7 days for Top Rated Sellers); withdrawals 1-3 business days via PayPal.",
 "Complete orders fast and use PayPal (1-3 days) once funds clear.",
 "The 14-day order clearance is the structural blocker."),
"R0491": ("weeks",
 "Fixed-price: funds released on client approval, or automatically 14 days after a release request; hourly: weekly invoice cycle.",
 "Hourly contracts pay on the weekly cycle — faster than the 14-day fixed-price hold.",
 "The 14-day release hold is the structural blocker for fixed-price work."),
"R0492": ("weeks",
 "Paid via direct bank deposit after you submit an invoice through the app; typically a few business days after task completion.",
 "Invoice the moment the task is done — the deposit lands within a few business days.",
 "Getting booked and completing tasks is the blocker; the payout leg itself is days."),
"R0493": ("weeks",
 "Clients pay you directly per project terms — Thumbtack does not pay pros.",
 "Win jobs with fast-paying clients and set short payment terms.",
 "Client acquisition and their payment terms are the structural blockers."),
"R0494": ("weeks",
 "Sweatcoin accrual is daily, but Sweatcoins cannot be redeemed for cash from SweatCo; any crypto path needs minting, exchange transfer, and sale with fees.",
 "Accumulate daily.",
 "No direct cash redemption exists — the structural blocker is the missing payout rail."),
"R0495": ("weeks",
 "Prize paid within ~7 days after the verified final weigh-in and referee certification; prize is algorithm-calculated.",
 "The prize lands within a week of the final weigh-in — the challenge itself is the long pole.",
 "The multi-week weight-loss challenge is the structural blocker."),
"R0496": ("weeks",
 "Paid after the final verified weigh-in; winners split the pot — payout only if you hit your goal.",
 "Hit the goal in the shortest challenge available.",
 "The multi-week betting pool is the structural blocker."),
"R0500": ("weeks",
 "Points credited daily; first gift-card redemption available 10 days after install, then anytime with enough points.",
 "Install and let daily points accrue; first redemption unlocks at day 10.",
 "The 10-day install gate is the structural blocker."),
"R0505": ("weeks",
 "Credit/progress accrues on reading each PaidEmail; email volume varies and is not guaranteed.",
 "Read every PaidEmail that arrives.",
 "Unpredictable, slow email volume is the structural blocker."),
"R0507": ("weeks",
 "Points accrue per read email; email volume and value vary and are not guaranteed.",
 "Read every points email.",
 "Unpredictable, slow email volume is the structural blocker."),
"R0521": ("weeks",
 "Daily checklist bonus credits when the day's checklist is complete; payouts via PayPal/gift cards once the cashout minimum is reached.",
 "Complete the daily checklist every day; cash out the moment you hit the minimum.",
 "Earning the cashout minimum takes days and redemption processing is unstated."),
"R0522": ("weeks",
 "Bonus points credit when you hit the day's challenge goal; redemptions via gift cards, PayPal, Venmo, bank transfer, or crypto.",
 "Hit daily challenges and redeem via the fastest available method (gift card/PayPal).",
 "Earning the minimum takes days and redemption processing is unstated."),
"R0528": ("weeks",
 "Coins credit per receipt scan; redeem from $3 (3,000 coins at Silver level); coins expire after 90 days without a valid paper receipt.",
 "Scan receipts daily and redeem at the $3 minimum.",
 "Redemption processing time is unstated in official terms."),
"R0534": ("weeks",
 "Points credit per linked purchase/survey; redeem via PayPal/Venmo once the minimum is met (3,000 points/$3 per current reviews).",
 "Link accounts for automatic points and redeem at the $3 minimum.",
 "Redemption processing time is unstated in official terms."),
"R0325": ("weeks",
 "Bonus posts after the friend enters the code and sends $5+ within 14 days; exact timing is shown in-app.",
 "Have the friend complete the $5 send in minutes — the bonus posts fastest right after qualification; the timing display is in-app.",
 "The friend's qualifying action is the trigger; official terms do not publish a payout clock."),
"R0326": ("weeks",
 "Reward credited within 30 days after the friend completes the $50+ qualifying spend.",
 "Have the friend complete the $50+ spend immediately; the reward credits within 30 days.",
 "The 30-day credit window is the structural blocker."),
"R0327": ("weeks",
 "Points issued after the friend's qualifying $5+ spend is confirmed (1,000 points = $10 cash back), per the PayPal Rewards Program Agreement.",
 "Friend spends $5 ASAP so the spend is confirmed; then redeem points for $10 cash back.",
 "Spend confirmation plus points redemption are the blockers."),
"R0328": ("weeks",
 "Milestone bonus credited approximately one week after claiming; stock sellable 3 trading days after grant; cash value withdrawable 60 days after claiming.",
 "Claim immediately; the stock grants ~1 week after claiming.",
 "The 60-day cash-withdrawal hold is the structural blocker."),
"R0329": ("weeks",
 "Paid within 7 business days after SoFi validates the funding, no later than 74 days after the funding date.",
 "Fund early and cleanly; the bonus lands ~1 week after validation.",
 "SoFi's funding-validation window is the structural blocker."),
"R0330": ("weeks",
 "Bonuses typically posted within 10 business days after the friend meets all requirements.",
 "Have the friend meet all requirements immediately.",
 "The friend's qualifying actions plus 10 business days are the blocker."),
"R0331": ("weeks",
 "Generally within 60 days of the friend's qualifying purchase, typically at the next quarterly Cash Back payment.",
 "Refer around a quarter boundary so the payment lands at the next quarterly run.",
 "The quarterly payout cadence is the structural blocker."),
"R0337": ("weeks",
 "150 units at friend signup; 350 more when the friend reaches Checkpoint 5; units have no official dollar conversion.",
 "Have the friend reach Checkpoint 5 fast; convert units to rewards.",
 "The friend's gameplay to Checkpoint 5 and unit conversion are the blockers."),
"R0339": ("weeks",
 "300 SB bonus credits the day after the referral qualifies (referral must earn 300 SB in 30 days); then redeem SB for gift cards/PayPal.",
 "Have the friend earn 300 SB fast — the bonus credits the next day.",
 "The friend's 30-day earning window plus SB redemption are the blockers."),
"R0341": ("weeks",
 "480-point bonus credits the day after qualification (referral earns 300 eligible points in 30 days); 750-point bonus after the friend's $20+ purchase.",
 "Have the friend earn 300 eligible points fast — the bonus credits the next day.",
 "The friend's qualification window plus redemption are the blockers."),
"R0831": ("weeks",
 "Reward generally issued within 1-2 business days after the 30-day qualification period.",
 "Complete qualification on day one; the clock then runs 30 days.",
 "The 30-day qualification period is the structural blocker."),
"R0832": ("weeks",
 "$15/month bill credit for 12 months, beginning after the 30-day qualification period.",
 "Complete qualification on day one.",
 "The 30-day qual plus monthly cadence is the structural blocker."),
"R0833": ("weeks",
 "Credits post no sooner than 15 days after the friend's activation.",
 "Activate immediately; the credit posts after 15 days.",
 "The 15-day wait is the structural blocker."),
"R0834": ("weeks",
 "Both sides receive the $25 virtual card 35 days after activation.",
 "Activate immediately.",
 "The 35-day wait is the structural blocker."),
"R0835": ("weeks",
 "Watts accumulate per event; cash out via the platform per its payout schedule.",
 "Join events and cash out on the platform's schedule.",
 "The platform payout schedule is the structural blocker."),
"R0836": ("weeks",
 "Boost applies for three months after the referred account is opened.",
 "Open and fund the referred account immediately.",
 "The three-month boost structure is the structural blocker."),
"R0837": ("weeks",
 "$20 service credit to both sides when an eligible friend buys a plan; timing is on the official terms page.",
 "Complete qualification fast, then check the official 'See terms' page for the exact payout clock.",
 "Timing is defined in official terms not re-fetched this pass — treated as weeks until confirmed."),
"R0840": ("weeks",
 "Paid per the promotion's payout schedule after qualification.",
 "Complete qualification fast.",
 "The promotion's payout schedule is the structural blocker."),
"R0841": ("weeks",
 "Statement credit within 1-3 billing periods after the qualifying purchase.",
 "Make the qualifying purchase early in the billing cycle.",
 "Billing cycles are the structural blocker."),
"R0843": ("weeks",
 "Bonus deposited within 21 days of the statement cycle end once the friend meets all requirements.",
 "Have the friend meet requirements early in the cycle.",
 "The statement cycle plus 21 days is the structural blocker."),
"R0844": ("weeks",
 "Allow 2-4 weeks after the friend's enrollment completes for email delivery of the gift cards.",
 "Complete enrollment fast; cards arrive by email in 2-4 weeks.",
 "The 2-4 week delivery window is the structural blocker."),
"R0845": ("weeks",
 "Credit applied once the friend completes 60 days of enrollment and remains an active customer.",
 "Enroll immediately.",
 "The 60-day enrollment is the structural blocker."),
"R0846": ("weeks",
 "Bill credit applied within two billing cycles after the friend completes 10 days of active service.",
 "Activate service immediately.",
 "Two billing cycles are the structural blocker."),
"R0847": ("weeks",
 "Credit applied within two billing cycles after the friend completes 10 days of active electricity service.",
 "Activate service immediately.",
 "Two billing cycles are the structural blocker."),
"R1973": ("weeks",
 "Cash or gift card payment per study (averaging ~$25/hour); payment timing is set per study.",
 "Do online studies (no travel); payment comes after the session.",
 "Study scheduling and per-study payment are the structural blockers."),
"R3564": ("weeks",
 "Annual program: apply typically October-December; award paid in the first quarter following the program year.",
 "Apply during the window and contribute during the program year.",
 "The annual cycle is the structural blocker."),
"R3565": ("weeks",
 "Annual program: application by May 31; minimum contribution by November 1 of the application year.",
 "Apply and contribute before the deadlines.",
 "The annual cycle is the structural blocker."),
"R3566": ("weeks",
 "Six months of $25+/month recurring contributions required to unlock the match (2026 promo ending 12/31/2026).",
 "Start the monthly contributions immediately.",
 "The six-month contribution run is the structural blocker."),
"R3567": ("weeks",
 "Annual cycle: apply April 1-July 31; contributions during the calendar year; match deposited the following January.",
 "Apply in-window and contribute during the year.",
 "The annual cycle is the structural blocker."),
"R3568": ("weeks",
 "Apply within 12 months of account opening; contributions within the same 12-month window earn the match.",
 "Contribute within the 12-month window.",
 "The 12-month window is the structural blocker."),
"R3570": ("weeks",
 "Reward paid within ~90 days after installation begins on the referee's system — months after the referral is made.",
 "Refer someone ready to install soon.",
 "The installation timeline plus 90 days is the structural blocker."),
"R3571": ("weeks",
 "Reward notification within 60 days of eligible activation; redemption within 75 days of notification; card delivered 3-4 weeks after redemption.",
 "Activate and watch for the notification; redeem immediately when it arrives.",
 "The 60-day notification plus 3-4 week delivery are the structural blockers."),
"R6441": ("weeks",
 "Annual cycle: contribute during the calendar tax year, then claim the credit when filing that year's Indiana income tax return.",
 "Contribute during the tax year and file on time.",
 "Tax filing is the structural blocker."),
"R6443": ("weeks",
 "2026 program year: application due December 1, 2026; qualifying contributions during calendar 2026; match deposited by January 31, 2027.",
 "Apply and contribute during 2026.",
 "The annual cycle is the structural blocker."),
"R6445": ("weeks",
 "Applications and qualifying deposits through June 30, 2026; match on deposits made August 1-June 30 of the qualifying period.",
 "Deposit during the qualifying window.",
 "The period end is the structural blocker."),
"R6446": ("weeks",
 "Annual cycle: applications September 1-December 31; approvals notified in April; scholarship units deposited by end of September.",
 "Apply in-window and meet minimum contributions by August 31.",
 "The annual cycle is the structural blocker."),
"R6447": ("weeks",
 "One-time grant: apply within one year of funding the account; maintain the contribution for three years.",
 "Fund and apply early.",
 "The multi-year maintenance is the structural blocker."),
"R6448": ("weeks",
 "One-time $100 grant deposited to the CollegeBound account; enroll within one year of birth or adoption.",
 "Enroll early; the $100 is deposited to the account.",
 "Enrollment paperwork is the structural blocker."),
"R0116": ("weeks",
 "Paid quarterly (February, May, August, November) once the balance reaches $5.01; smaller balances roll forward.",
 "Stack purchases so the balance clears $5.01 before a payout month.",
 "The quarterly cadence is the structural blocker."),
"R0117": ("weeks",
 "Cashback usually appears within ~7 days of purchase; becomes payable after the retailer's return period and commission confirmation.",
 "Shop retailers with short return windows; there is no general payout minimum — redeem as soon as it's payable.",
 "Merchant return periods are the structural blocker."),
"R0121": ("weeks",
 "Pending within a few days; typically confirmed 3-14 weeks after purchase; paid quarterly once the balance reaches $5.01.",
 "Confirm early purchases so they clear before a payout date.",
 "The 3-14 week confirmation plus quarterly cadence are the structural blockers."),
"R0125": ("weeks",
 "Rewards typically post 30-90 days after purchase (~90 days after completed travel); $5.00 minimum to redeem for e-gift cards.",
 "Book travel/purchases early; redeem at the $5 minimum as soon as posted.",
 "The 30-90 day posting window is the structural blocker."),
"R0126": ("weeks",
 "Points credit after eligible purchases are confirmed; redemption thresholds are offer-dependent; points expire after 12 months of inactivity.",
 "Confirm purchases fast; redeem at the lowest available threshold.",
 "Purchase confirmation lag plus unstated redemption speed are the blockers."),
"R0134": ("weeks",
 "Cash back becomes available after the 90-day return window; processing 1-5 business days after confirmation; $10 available minimum.",
 "Shop early; the clock runs 90 days from purchase.",
 "The 90-day return window is the structural blocker."),
"R0135": ("weeks",
 "Merchant initially confirms in 2-7 days; cashback becomes available after the return period; $10 available-balance minimum to withdraw.",
 "Shop retailers with short return periods.",
 "The return period is the structural blocker."),
"R0136": ("weeks",
 "Pending generally 90 days (can exceed depending on the merchant); $10 minimum balance to withdraw via check or PayPal.",
 "Shop early; withdraw at the $10 minimum.",
 "The 90-day pending period is the structural blocker."),
"R0140": ("weeks",
 "Digital gift cards may take up to 10 business days (usually arrive sooner).",
 "Redeem for a digital gift card — usually arrives well before the 10-business-day max.",
 "The up-to-10-business-day redemption window is the structural blocker."),
"R0145": ("weeks",
 "1,000 GrabPoints points convert to $1; minimum redemption 3,000 points ($3). Payout timing not stated on the official conversion page.",
 "Cash out at the $3 minimum as soon as you hit it.",
 "Official payout timing is unstated — treated as weeks until confirmed."),
"R0461": ("weeks",
 "$10 payable minimum; cash back becomes payable after merchant validation/return periods; payments below minimum incur a $3 fee.",
 "Hit $10 via short-return-period merchants and request in one go.",
 "Merchant validation/return periods are the structural blockers."),
"R0462": ("weeks",
 "After merchant confirmation (varies by store); no quarterly payment schedule.",
 "Cash out as soon as rebates are confirmed — no quarterly wait.",
 "Merchant confirmation is the structural blocker."),
"R0463": ("weeks",
 "Pending rebates wait 90 days; all payments sent at the beginning of each month for the previous month's requests.",
 "Request at month start once the 90 days clear.",
 "The 90-day pending plus monthly send are the structural blockers."),
"R0464": ("weeks",
 "Merchants report orders in 1-7 days; payments typically within five business days after the request.",
 "Request payout the day rebates post — the money lands within ~5 business days of the request.",
 "Merchant reporting plus the request cycle keep this past a week end-to-end."),
"R0465": ("weeks",
 "Merchant tracking takes hours to days; payout processing varies by method; $10 in available cashback required (first cash-out needs a rebate order).",
 "Hit $10 with a rebate order included; choose PayPal or gift card at cashout.",
 "Tracking plus variable payout processing are the blockers."),
"R0466": ("weeks",
 "After merchant confirmation (merchant-side delays explicitly possible); $20 minimum; paid by check, PayPal, Alipay, or other options.",
 "Hit the $20 minimum and pick PayPal for the fastest leg.",
 "Merchant confirmation plus the $20 minimum are the structural blockers."),
"R0467": ("weeks",
 "Rebates pending normally 90 days; some merchants take longer than 90 days.",
 "Shop merchants with the shortest pending terms.",
 "The 90-day pending period is the structural blocker."),
"R0530": ("weeks",
 "Cash back posts up to 7 days after the in-store purchase; Rakuten pays out quarterly (Big Fat Check) via PayPal/check.",
 "Link cards and shop in-store; the quarterly check is the payout clock.",
 "The quarterly payout cadence is the structural blocker."),
"R7302": ("weeks",
 "$5 bonus with first purchase; payout requestable once available rebates exceed $10 — checks paid monthly (usually the 1st).",
 "Get the first purchase in early so the $5 bonus is available for the next monthly run.",
 "The monthly check run is the structural blocker."),
"R1522": ("weeks",
 "Rewards issued once per month, within the first 48 hours of the following month; receipts must be shared by month end.",
 "Submit receipts before the month-end deadline.",
 "The monthly issuance is the structural blocker."),
}
